name: Weather Report
on: [workflow_dispatch]  # Run manually

jobs:
  generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: pip install requests
      
      - name: Run weather parser
        env:
          API_KEY: ${{ secrets.API_KEY }}  # Set in repo settings
        run: python examples/weather_parser.py
        
      - name: Run weather parser and save output
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python examples/weather_parser.py > weather_report.txt  # Save output to file

      - name: Upload weather report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: weather-report
          path: weather_report.txt
